version: '2.4'
services:
  procon:
    container_name: ${INSTANCE_NAME}
    build:
      context: .
    tty: true
    mem_limit: 2G
    restart: on-failure
    image: prophet731/procon:portainer
    command: /opt/procon/create_game_conn.sh -gip ${PROCON_GAMESERVER_IP} -gp ${PROCON_GAMESERVER_PORT} -grp ${PROCON_GAMESERVER_PASS}
