version: '2'
services:
  procon:
    build:
      context: .
    ports:
      - "${LAYER_PORT}:27260"
    tty: true
    mem_limit: 2G
    restart: on-failure
    image: prophet731/procon:latest
    dns: 1.1.1.1
    entrypoint: ./entrypoint.sh
