version: '2.4'
services:
  procon:
    container_name: ${INSTANCE_NAME}
    build:
      context: .
    ports:
      - 27260
    tty: true
    mem_limit: 2G
    restart: on-failure
    image: prophet731/procon:portainer

