version: '2.4'
services:
  procon:
    build:
      context: .
    ports:
      - "${LAYER_PORT}:27260"
    tty: true
    mem_limit: 2G
    restart: on-failure
    image: prophet731/procon:portainer
    entrypoint: ["./entrypoint.sh", "-gip", "${PROCON_GAMESERVER_IP}", "-gp", "${PROCON_GAMESERVER_PORT}", "-grp", "${PROCON_GAMESERVER_PASS}"]
